name: Chaining-job

on:
  workflow_dispatch:
    inputs:
      run-job-3:
        description: Runs job 3
        required: true
        type: boolean
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Output job 1
        run: echo "Hello from job 1. Run job 3 equal = ${{ github.event.inputs.run-job-3 }}"

      
  job-2:
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output job 2
        run: echo "Hello from job 2."

  job-3:
    if: github.event.inputs.run-job-3 = 'true'
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output job 3
        run: echo "Hello from job 3."


    
  
