name: Variable and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: Person to greet
        required: true
        default: world
        type: string

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dump github context.'
        env:
          GITHUB_TOKEN: ${{ toJSON(github) }}
        run: echo "$GITHUB_TOKEN"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Job 2'
        run: echo "Hello Mr. ${{ github.event.inputs.name }}"
      
